### ISSUE TITLE
This must be a bug, lua panic for a trivial binding.

### ISSUE THREAD

**Issue by yihuang** [SteveKChiu/lua-intf#106]
https://gist.github.com/yihuang/cac3e28cbf103c40c151

**Comment by yihuang** [comment]
I've fixed it.
1、Need a overloaded ``Lua::push`` for ``const char*`` without ``len``
2、Need to ``beginModule`` before ``addConstants``

**Comment by SteveKChiu** [comment]
Root module is special, `lua-intf` only accept `beginModule` and `beginClass` for that, any other may not work as expected.

And there is really no reason to use other calls, if you want to add function or value to globals, just use `Lua::setGlobal` to do that.

I may update the LuaBinding(L) later to reflect this.

**Comment by SteveKChiu** [comment]
Another reason is `lua-intf` need to override some meta functions, so we need a table (module) to adapt those meta functions, adding those meta functions to globals directly is a very bad idea.

**Comment by inDigiNeous** [comment]
I'm seeing this also. 

PANIC: unprotected error in call to Lua API (bad argument #-1 (table expected, got nil))

This didn't happen with version I checked out some time ago.  Unfortunately I don't have the .git subdirectory in my checkout, but the date on directory says November 18th.

Was just wondering why my bindings was working in a test project, but when I checked out the new version couple of days ago to my other project, gives this panic.

**Comment by SteveKChiu** [comment]
OK,
the LuaBinding interface has been refined, it no longer exports invalid binding methods, all you can do now is `beginModule`, `beginClass` and `addFunction`, all other bindings that requires meta table are removed from the interface.

And the last commit of remove char* mapping may cause problem if you are using char array or using char* as return value. Since it is common, I have added back the char* mapping (for push only).

**Comment by SteveKChiu** [comment]
It seems to be resolved, please re-open if you still have problem.
