### ISSUE TITLE
Support for vector<string>

### ISSUE THREAD

**Issue by cochin98** [SteveKChiu/lua-intf#65]
My class have a vector<string> in it. Does the wrapper support this type?

**Comment by SteveKChiu** [comment]
Not directly, no container type is directly supported. However, you can:

1. use LuaRef instead of vector<string>

2. use LuaRef to catch the Lua value, and use `Lua::getList<vector<string>>(ref)` to convert it to vector<string>, or `Lua::pushList(L, my_vector)` to push the value.

````c++
void my_func_need_vector_string(LusRef ref)
{
    vector<string> list = Lua::getList<vector<string>>(ref);
    ...
}
````

3. define your own LuaTypeMapping<>

````c++
template <typename T>
LuaTypeMapping <vector<T>>
{
static void push(lua_State* L, const vector<T>& v)
    {
        if (v.empty()) {
            lua_newtable(L);
        } else {
            Lua::pushList(L, v);
        }
    }

    static vector<T> get(lua_State* L, int index)
    {
        if (lua_isnoneornil(L, index)) {
            return vector<T>();
        } else {
            return Lua::getList<vector<T>>(L, index);
        }
    }

    static vector<T> opt(lua_State* L, int index, const vector<T>& def)
    {
        if (lua_isnoneornil(L, index)) {
            return def;
        } else {
            return Lua::getList<vector<T>>(L, index);
        }
    }
};
````

And why not support it out of box? Because:

1. LuaRef is almost always better

2. it is expensive in term of runtime cost

3. there is too many container, and you probably only use a few. And sometimes you need special allocator, that does not fit with default.

**Comment by SteveKChiu** [comment]
Now you can simply declare the following to use std::vector with the latest commit:

````c++
LUA_USING_LIST_TYPE(std::vector)
````

**Comment by SteveKChiu** [comment]
This seems to be resolved, please open new issue if you have more questions.
